jdk_version                                = 11
enable_datadog                             = true
datadog_agent_version                      = "7"
datadog_api_key                            = "<DataDog API Key>"
datadog_site                               = "<DataDog Site e.g. us3.datadoghq.com>"
datomic_account_user                       = "<Datomic account user>"
datomic_account_password                   = "<Datomic account password>"
datomic_version                            = "<Datomic version e.g. 1.0.6397>"
datomic_custom_metric_callback_library_url = "https://repo.clojars.org/net/clojars/fr33m0nk/datomic-datadog-reporter/1.1.5/datomic-datadog-reporter-1.1.5.jar"
